# Audit all gems listed in the Gemfile for known security problems by running bin/bundler-audit.
# CVEs that are not relevant to the applicationJs can be enumerated on the ignore list below.

ignore:
  - CVE-THAT-DOES-NOT-APPLY
